AdvertisingBillboard.Web/Models/AdministratorPageViewModel.cs
using AdvertisingBillboard.Domain;

namespace AdvertisingBillboard.Web.Models
{
    public class AdministratorPageViewModel
    {   
        public UserViewModel[] Users { get; set; }
        public Device[] Devices { get; set; }
        public Video[] Videos { get; set; }
        
    }
}

AdvertisingBillboard.Web/Models/UserViewModel.cs
using System;
using AdvertisingBillboard.Domain;

namespace AdvertisingBillboard.Web.Models
{
    public class UserViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Device[] Devices { get; set; }
    }
}

AdvertisingBillboard.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using AdvertisingBillboard.Domain;
using AdvertisingBillboard.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisingBillboard.Web.Controllers
{
    public class AdminController : Controller
    {
        private readonly IUsersRepository _usersRepository;
        private readonly IDevicesRepository _devicesRepository;
        private readonly IVideosRepository _videosRepository;

        public AdminController(
            IUsersRepository usersRepository,
            IDevicesRepository devicesRepository,
            IVideosRepository videosRepository)
        {
            _usersRepository = usersRepository;
            _devicesRepository = devicesRepository;
            _videosRepository = videosRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var users = _usersRepository.Get();
            var devices = _devicesRepository.Get();
            var videos = _videosRepository.Get();


            var usersViewModels = new List<UserViewModel>();
            foreach (var user in users)
            {
                usersViewModels.Add(new UserViewModel
                {
                    Id = user.Id,
                    Name = user.Name,
                    Devices = _devicesRepository.Get(user.Id)
                });
            }

            var vm = new AdministratorPageViewModel
            {
                Users = usersViewModels.ToArray(),
                Devices = devices,
                Videos = videos
            };

            return View(vm);
        }

        [HttpGet]
        public PartialViewResult Users()
        {
            return PartialView();
        }
        [HttpGet]
        public PartialViewResult Videos()
        {
            return PartialView();
        }

        [HttpGet]
        public PartialViewResult Devices()
        {
            return PartialView();
        }

        public ActionResult NotExistingName()
        {
            return View("~/Views/Admin/NotExistingName.cshtml");
        }
    }
}

AdvertisingBillboard.Web/Controllers/AuthController.cs
using AdvertisingBillboard.Domain;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisingBillboard.Web.Controllers
{
    public class AuthController :Controller
    {
        private readonly IUsersRepository _usersRepository;
        
        public AuthController(IUsersRepository usersRepository)
        {
            _usersRepository = usersRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string userName)
        {
            return View();
        }


        public ActionResult EnterAsUser(string userName)
        {
            foreach (var user in _usersRepository.Get())
            {
                if (userName.ToLower().Equals(user.Name.ToLower())) {
                    ViewBag.userName = userName;
                    return RedirectToAction("Get", "Users", new { name = userName });
                }
            }
            return View("~/Views/Shared/ErrorWrongName.cshtml");
        }
    }
}

AdvertisingBillboard.Web/Controllers/DeviceController.cs
using AdvertisingBillboard.Domain;
using Microsoft.AspNetCore.Mvc;

namespace AdvertisingBillboard.Web.Controllers
{
    public class DeviceController : Controller
    {
        private readonly IDevicesRepository _devicesRepository;
        private readonly IUsersRepository _usersRepository;

        public DeviceController(IDevicesRepository devicesRepository, IUsersRepository usersRepository)
        {
            _devicesRepository = devicesRepository;
            _usersRepository = usersRepository;
        }

        [HttpPost]
        public RedirectResult Delete(string name)
        {
            _devicesRepository.Delete(name);
            return Redirect("~/Admin/Index");
        }

        public ActionResult Add(string deviceName, double memoryValue, string userName)
        {
            User tempUser = _usersRepository.Get(userName);
            foreach (Device device in _devicesRepository.Get())
            {
                if (device.Name == deviceName)
                {
                    return View("~/Views/Admin/SameNameDevice.cshtml");
                }
            }
            Device tempDevice = new Device() { Name = deviceName, Memory = memoryValue, User = tempUser };
            _devicesRepository.Create(tempDevice);
            tempUser.Devices.Add(tempDevice);
            return Redirect("/Admin/Index");
        }
    }
}

AdvertisingBillboard.Web/Controllers/UsersController.cs
using AdvertisingBillboard.Domain;
using AdvertisingBillboard.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace AdvertisingBillboard.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUsersRepository _usersRepository;
        private readonly IDevicesRepository _devicesRepository;

        public UsersController(
            IUsersRepository usersRepository,
            IDevicesRepository devicesRepository)
        {
            _usersRepository = usersRepository;
            _devicesRepository = devicesRepository;
        }

        [HttpGet]
        public IActionResult Get(string name)
        {
            var user = _usersRepository.Get(name);
            var devices = _devicesRepository.Get(user.Id);

            var vm = new UserViewModel
            {
                Id = user.Id,
                Name = user.Name,
                Devices = devices
            };
            
            return View(vm);
        }

        [HttpPost]
        public ActionResult Add(string name)
        {
            foreach (User user in _usersRepository.Get())
            {
                if (user.Name == name)
                {
                    return View("~/Views/Admin/SameNameUser.cshtml");
                }
            }
            _usersRepository.Create(new User
            {
                Id = Guid.NewGuid(),
                Name = name,
                Devices = new List<Device>()
            });

            return Redirect("/Admin/Index");
        }

        [HttpPost]
        [ActionName("delete")]
        public RedirectResult Delete(Guid id)//delete user and his videos
        {
            _usersRepository.Delete(id);
            _devicesRepository.Delete(id);
            return Redirect("~/Admin/Index");
        }
    }
}

AdvertisingBillboard.Web/Controllers/VideosController.cs
using AdvertisingBillboard.Domain;
using Microsoft.AspNetCore.Mvc;


namespace AdvertisingBillboard.Web.Controllers
{
    public class VideosController : Controller
    {
        private readonly IVideosRepository _videosRepository;
        private readonly IDevicesRepository _devicesRepository;

        public VideosController(IVideosRepository videosRepository, IDevicesRepository devicesRepository) {
            _videosRepository = videosRepository;
            _devicesRepository = devicesRepository;
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Upload(string videoAddress, string videoName, string deviceName)
        {
            var device = _devicesRepository.Get(deviceName);
            Video video = new Video
            {
                Name = videoName,
                Address = videoAddress,
                Device = device
            };

            _videosRepository.Create(video);
            return Redirect("/Admin/Index");
        }


        [HttpPost]
        [ActionName("delete")]
        public RedirectResult Delete(string name)
        {
            _videosRepository.Delete(_videosRepository.Get(name));
            return Redirect("/Admin/Index");
        }
    }
}

AdvertisingBillboard.Web/Views/Admin/Devices.cshtml
@using AdvertisingBillboard.Domain
@using AdvertisingBillboard.Web.Models
@model AdvertisingBillboard.Web.Models.AdministratorPageViewModel
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<div class="container">
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#add_device">Add device</button>

    <!-- Modal -->
    <div id="add_device" class="modal fade in active" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Add device</h3>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form method="post" action="~/Device/Add" name="addDevice">
                        <input placeholder="Name" name="deviceName" required /> <br /> <br />
                        <input placeholder="Memory value" name="memoryValue" required /> <br /><br />
                        <select size="1" name="userName" required>
                            @foreach (UserViewModel user in Model.Users)
                            {
                                <option>@user.Name</option>
                            }
                        </select>
                        <br /><br />
                        <input type="submit" class="btn btn-success" value="Submit" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    <button class="btn btn-success">Create new group</button>
    <button class="btn btn-success">Upload a timetable</button>
    <button class="btn btn-warning">Export the timetable</button>
    <br> <br>
    <table class="table">
        <tr>
            <th>Device name</th>
            <th>Memory</th>
            <th>User</th>
            <th></th>
        </tr>
        @{
            foreach (Device device in Model.Devices)
            {
                <tr>
                    <td>@device.Name</td>
                    <td>@device.Memory</td>
                    <td>@device.User.Name</td>
                    <td>
                        <form method="post" action="@Url.Action("Delete", "Device", new {name = device.Name })">
                            <button type="submit" class="btn btn-danger" value="Submit">
                                Delete device
                            </button>
                        </form>
                    </td>
                </tr>
            }
        }
    </table>
</div>

AdvertisingBillboard.Web/Views/Admin/NotExistingName.cshtml
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}
<br>
<div class="container col-6">
    <h5>There is no user with such name.</h5>
    <input type="button" value="Return to Admin Page" class="button btn-default col-12" onclick="location.href='@Url.Action("Index", "Admin")'" />
</div>

AdvertisingBillboard.Web/Views/Admin/SameNameDevice.cshtml

@{
    ViewData["Title"] = "Same Name Device";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<br>
<div class="container col-6">
    <h5>You can't add a device with the same name.</h5>
    <input type="button" value="Return to Admin Page" class="button btn-default col-12" onclick="location.href='@Url.Action("Index", "Admin")'" />
</div>


AdvertisingBillboard.Web/Views/Admin/SameNameUser.cshtml

@{
    ViewData["Title"] = "Same Name User";
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<br>
<div class="container col-6">
    <h5>User with such name already exists.</h5>
    <input type="button" value="Return to Admin Page" class="button btn-default col-12" onclick="location.href='@Url.Action("Index", "Admin")'" />
</div>


AdvertisingBillboard.Web/Views/Admin/Users.cshtml
@using AdvertisingBillboard.Domain
@using AdvertisingBillboard.Web.Models
@model AdvertisingBillboard.Web.Models.AdministratorPageViewModel
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<div class="container">
    <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#add_user">
        Add user
    </button>

    <br>
    <br>

    <table class="table">
        <tr>
            <th>ID</th>
            <th>User's name</th>
            <th>Devices</th>
            <th></th>
        </tr>
        <tr>
            @{
                foreach (UserViewModel user in Model.Users)
                {
                <tr>
                    <td>@user.Id</td>
                    <td>@user.Name</td>
                    <td>
                        <ul>
                            @foreach (Device device in user.Devices)
                            {
                                <li>@device.Name</li>
                            }
                        </ul>
                    </td>
                    <td>
                        <!--HOW TO DELETE VIDEO? -->
                        <form method="post" action="@Url.Action("Delete", "Users", new {id = user.Id })">
                            <button type="submit" class="btn btn-danger" value="Submit">
                                Delete user
                            </button>
                        </form>
                    </td>
                </tr>
            }
            }
        </tr>
    </table>
</div>


    <!-- Modal -->
    <div id="add_user" class="modal fade in active" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Add user</h3>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <form method="post" action="~/Users/Add">
                        <input placeholder="Name" name="name" required />
                        <br />
                        <br />
                        <input type="submit" class="btn btn-success" value="Submit" />
                    </form>
                </div>
            </div>
        </div>
    </div>

AdvertisingBillboard.Web/Views/Admin/Videos.cshtml
@using AdvertisingBillboard.Domain
@using AdvertisingBillboard.Web.Models
@model AdvertisingBillboard.Web.Models.AdministratorPageViewModel
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<div id="videos" class="container">
    <br>
    <div class="container">
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#uploadVideo">Upload video</button> <br /> <br />

        <!-- Modal -->
        <div id="uploadVideo" class="modal fade in active" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Upload Video</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="~/Videos/Upload" name="uploadVideo">
                            <input class="text" type="text" name="videoName" placeholder="Name of the video" required /> <br><br>
                            <select name="deviceName" required>
                                @{
                                    foreach (UserViewModel user in Model.Users)
                                    {
                                        <option disabled>
                                            @user.Name
                                        </option>
                                        foreach (Device device in user.Devices)
                                        {
                                            <option>
                                                @device.Name
                                            </option>
                                        }
                                    }
                                }
                            </select> <br><br>
                            <input class="btn btn-default" type="file" name="videoAddress" required /><br><br>
                            <input class="btn btn-success" type="submit" value="Submit" />
                            <br /><br />
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <table class="table">
            <tr>
                <th>Video</th>
                <th></th>
            </tr>
            @foreach (var currentVideo in Model.Videos)
            {
                <tr>
                    <td>
                        <a href="~/video/@currentVideo.Address">@currentVideo.Name</a>
                    </td>
                    <td>
                        <form method="post" action="@Url.Action("Delete", "Videos", new {name = currentVideo.Name })">
                            <button type="submit" class="btn btn-danger" value="Submit">
                                Delete video
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

AdvertisingBillboard.Web/Views/Admin/index.cshtml
@model AdvertisingBillboard.Web.Models.AdministratorPageViewModel
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<br />
<a class="button btn-primary col-2" href="@Url.Action("Index", "Auth")">Return to Authentification Page</a>
<br />

<div class="row">
    <span class="col-2"></span>
    <span class="col-3">Number of users: @Model.Users.Length</span>
    <span class="col-3">Number of devices: @Model.Devices.Length</span>
    <span class="col-2">Number of videos: @Model.Videos.Length</span>
    <span class="col-2"></span>
</div>
<br>


<ul class="nav nav-tabs">
    <li class="col-2"></li>
    <li class="active col-3">
        <a data-toggle="tab" href="#users">Users</a>
    </li>
    <li class="active col-3">
        <a data-toggle="tab" href="#devices">Devices</a>
    </li>
    <li class="active col-2">
        <a data-toggle="tab" href="#videos">Videos</a>
    </li>
    <li class="col-2"></li>
</ul>
<div class="tab-content">
    <div id="users" class="tab-pane fade ">
        <br />
        @Html.Partial("Users")
    </div>
    <div id="devices" class="tab-pane fade">
        <br />
        @Html.Partial("Devices")
    </div>
    <div id="videos" class="tab-pane fade">
        <br />
        @Html.Partial("Videos")
    </div>
</div>





        <!-- Modal -->
        <div id="access_device" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Device Name</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Device status: <span>default</span></p>
                        <input type="button" class="btn btn-warning" value="Configure Memory"></input> <br> <br>
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Add device to the group <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1st group</a></li>
                                <li><a href="#">2nd group</a></li>
                            </ul> <br> <br>
                            <input type="button" class="btn btn-warning" value="Choose Video"> <br> <br>
                            <input type="button" class="btn btn-warning" value="Edit the timetable"></input>
                        </div>
                    </div>
                </div>

            </div>
        </div>


        <!-- Modal -->
        <div id="access_group" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title">Group Name</h3>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Group status: <span>default</span></p>
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Add device to the group <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="#">1st device</a></li>
                                <li><a href="#">2nd device</a></li>
                            </ul> <br> <br>
                            <input type="button" class="btn btn-warning" value="Choose Video"></input> <br> <br>
                            <input type="button" class="btn btn-warning" value="Edit the timetable"></input> <br> <br>
                            <table class="table">
                                <tr>
                                    <th>Device name</th>
                                    <th></th>
                                </tr>
                                <tr>
                                    <th>Default_Name</th>
                                    <th>
                                        <input type="button" class="btn btn-danger" value="Delete device"></input>
                                    </th>
                                </tr>
                            </table>
                            <input type="button" class="btn btn-danger" value="Delete group"></input>

                        </div>
                    </div>
                </div>

            </div>
        </div>

AdvertisingBillboard.Web/Views/Shared/DefaultLayout.cshtml

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Adv. App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    @RenderBody()
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

AdvertisingBillboard.Web/Views/Shared/ErrorWrongName.cshtml
@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}
<br>
<div class="container col-6">
    <h5>There is no user with such name.</h5>
    <input type="button" value="Return to Authorization Page" class="button btn-default col-12" onclick="location.href='@Url.Action("Index", "Auth")'" />
</div>

AdvertisingBillboard.Web/Views/Users/Get.cshtml
@model AdvertisingBillboard.Web.Models.UserViewModel

@{
    Layout = "~/Views/Shared/DefaultLayout.cshtml";
}

<br />
<a class="button btn-primary col-2" href="@Url.Action("Index", "Auth")">Return to Authentification Page</a>
<br />


<div class="container">
    <br />
    <div class="row">
        <input type="button" class="btn btn-primary col-2" value="Export timetable" />
        <span class="col-6"></span>
        <h5 class="col-4">Welcome, @Model.Name</h5>
    </div> <br />

    <ul class="nav nav-tabs">
        <li class="col-2"></li>
        <li class="active col-3">
            <a data-toggle="tab" href="#deviceList">Device List</a>
        </li>
        <li class="active col-3">
            <a data-toggle="tab" href="#adv_timetable">Check Advertising Timetable</a>
        </li>
        <li class="active col-2">
            <a data-toggle="tab" href="#videos_table">Videos</a>
        </li>
        <li class="col-2"></li>
    </ul>



    <div class="tab-content">
        <div id="deviceList" class="tab-pane fade container">
            <table class="table">
                <table class="table">
                    <tr>
                        <th>Device name</th>
                        <th></th>
                    </tr>
                    @{ foreach (var device in Model.Devices)
                        {
                            <tr>
                                <td>
                                    @device.Name
                                </td>
                                <td>
                                    <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#user_access_device">Get access</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <table class="table">
                    <tr>
                        <th>Device Group name</th>
                        <th></th>
                    </tr>
                    <tr>
                        <td>Any name</td>
                        <td>
                            <button type="button" class="btn btn-success btn-md" data-toggle="modal" data-target="#user_access_group">Get access</button>
                        </td>
                    </tr>

                </table>
            </table>
        </div>
        <div class="tab-pane fade container" id="adv_timetable">
            <table class="table">
                <tr>
                    <th>Device name</th>
                    <th>Video</th>
                    <th>Time</th>
                    <th>Date</th>
                </tr>
                <tr>
                    @{
                        foreach (var device in Model.Devices)
                        {
                        <tr>
                            <td>
                                @device.Name
                            </td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                        </tr>
                    }
                    }
                    </tr>
                </table>
            </div>
            <div id="videos_table" class="tab-pane fade container">
                <table class="table">
                    <tr>
                        <th>Video</th>
                        <th>Amount of clicks</th>
                        <th>Amount of views</th>
                        <th>Working time</th>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>3</td>
                        <td>4</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>